export { default as About } from '../pages/About'
export { default as Home } from '../pages/Home'
export { default as Blog } from '../pages/Blog'
export { default as Notfound } from '../pages/Notfound'
export { default as EditPost } from '../pages/EditPost'
export { default as Layout } from './Layout'
export { default as Singlepage } from './Singlepage'